### PR TITLE
Multiple zoomfloppy support

### PR DESCRIPTION
**Pull request by zoggins**

### CODE REVIEW

**Comment by sjgray** [comment]
Hi, should I ignore this? why was it closed?

**Comment by zoggins** [comment]
I wasn't aiming at your branch yet, I was aiming for my forked master.  The changes aren't quite ready for prime time. :)

**Comment by sjgray** [comment]
Ok. Those new dropdowns make things a little messy though...

**Comment by zoggins** [comment]
Yeah... UI is not my strong suite :)

**Comment by mnaberez** [comment]
I think having support for multiple ZoomFloppy devices in CBM-Transfer is a good idea.  If opencbm supports it, then it's probably reasonable for CBM-Transfer to support it.

What's your use case for multiple ZoomFloppy interfaces?  Are you using IEC and IEEE-488 drives at the same time?  Just curious, since I saw your thread about multiple ZoomFloppy devices on the [zoomfloppy-users](https://groups.google.com/forum/#!forum/zoomfloppy-users) list also.

**Comment by sjgray** [comment]
I actually wanted to add support a while ago, but couldn't get my minizum to work. I assumed it was defective. Anyway, I'm all for adding support, and don't worry I can handle the GUI ;-)

**Pull request closed without merging**
